/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo.java;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class LibraryTest {
   @Test public void testingInsertionMethod() {
      Library lib = new Library();
      List<Integer> unsortedList = new ArrayList<>();
      unsortedList.add(5);
      unsortedList.add(2);
      unsortedList.add(9);
      unsortedList.add(1);
      unsortedList.add(3);

      System.out.println(unsortedList);


      List<Integer> sortedList = lib.insertionSort(unsortedList);

      assertEquals(1, sortedList.get(0).intValue());
      assertEquals(2, sortedList.get(1).intValue());
      assertEquals(3, sortedList.get(2).intValue());
      assertEquals(5, sortedList.get(3).intValue());
      assertEquals(9, sortedList.get(4).intValue());

      System.out.println(sortedList);
   }
}
