/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo.java;
import java.util.ArrayList;
import java.util.List;

public class Library {


    public List<Integer> insertionSort(List<Integer> unsortedList) {
        List<Integer> sortedList = new ArrayList<>();
        for (int i = 0; i < unsortedList.size(); i++) {
            int currentElement = unsortedList.get(i);
            int j = i - 1;
            while (j >= 0 && sortedList.get(j) > currentElement) {
                j--;
            }
            sortedList.add(j + 1, currentElement);
        }
        return sortedList;
    }

    public List<Integer> mergeSort(List<Integer> unsortedList) {
        return List.of(0);
    }
}
